PP-13440 upgrade modules to dropwizard_4
alphagov/pay-java-commons pull request #969
Opened 2024-12-27 14:16 UTC by SandorArpa

Upgrade modules to dropwizard 4.

To assure a smotth transition, create clone modules and update clones to Dropwizard 4 (and Jakarta if needed). The root pom file should not be updated to Dropwizard 4 just yet. Once all projects are using Dropwizard 4, then update root pom file and remove unused modules, and Dropwizard 4 explicit dependency from sub-modules.

2025-01-15 16:13 UTC, katstevens commented on testing-dropwizard-4/pom.xml
> +        <pact.version>4.0.10</pact.version>
Does this version need bringing up to date (not necessarily in this pull request)? I see in Connector and Webhooks we're using `<pact.version>4.6.16</pact.version>` - and [that it usually gets updated in those repos by Dependabot](https://github.com/alphagov/pay-connector/commit/d6a50f6b1ca83b9d1e61d7d6787216241264b097#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8R13). But in Adminusers it's still on v3.x. Any ideas what's going on there?

2025-01-15 16:20 UTC, SandorArpa commented on testing-dropwizard-4/pom.xml
> +        <pact.version>4.0.10</pact.version>
In adminusers it's an unused version property, it's actually using:
`<groupId>au.com.dius.pact.provider</groupId>
  <artifactId>maven</artifactId>
  <version>4.6.16</version>`

2025-01-15 16:22 UTC, SandorArpa commented on testing-dropwizard-4/pom.xml
> +        <pact.version>4.0.10</pact.version>
I'll test locally if we can upgrade pay-java-commons to 4.6.16

2025-01-15 16:29 UTC, SandorArpa commented on testing-dropwizard-4/pom.xml
> +        <pact.version>4.0.10</pact.version>
Ahh, ok I got it 🤦 
In other projects we use the provider and/or consumer framework 4.6.16). Here we have the jvm framework (latest 4.0.10)

`<groupId>au.com.dius.pact.consumer</groupId>`
  `<artifactId>junit</artifactId>`
vs
`<groupId>au.com.dius</groupId>`
 `<artifactId>pact-jvm-provider-junit</artifactId>`

2025-01-15 16:49 UTC, katstevens commented on testing-dropwizard-4/pom.xml
> +        <pact.version>4.0.10</pact.version>
Aha, that makes sense. Thanks for checking @SandorArpa!

2025-02-12 12:42 UTC, alexbishop1 requested changes
For the most part, this PR is making unchanged copies of files to create Dropwizard 4 parallels of the existing modules, which makes it hard to see the actual changes in GitHub.

To make life easier for me, I’ve marked places where the two variants of the file actually differ with _Actual change_. I’m happy with all of these, except possibly adding in the Dropwizard Dependencies BOM since that will presumably be handled by the projects that end up using these modules.

The other comments are mostly queries about added or changed dependencies. There’s also a few places where we’ve upgraded to a newer version of a dependency since this branch was created.

But overall I think this is straightforward enough, despite its apparent size.

2025-02-12 12:42 UTC, alexbishop1 commented on model-dropwizard-4/pom.xml
> +    </dependencyManagement>
_Actual change_

2025-02-12 12:42 UTC, alexbishop1 commented on model-dropwizard-4/pom.xml
> +        </dependency>
_Actual change_

2025-02-12 12:42 UTC, alexbishop1 commented on model-dropwizard-4/pom.xml
> +        </dependency>
_Actual change_

2025-02-12 12:42 UTC, alexbishop1 commented on model-dropwizard-4/pom.xml
> +        </dependency>
Why do we need this? Hibernate Validator should be packaged with Dropwizard.

2025-02-12 12:42 UTC, alexbishop1 commented on model-dropwizard-4/pom.xml
> +        </dependency>
What is this for?

2025-02-12 12:42 UTC, alexbishop1 commented on model-dropwizard-4/src/main/java/uk/gov/service/payments/commons/api/validation/AllowedStrings.java
> +import jakarta.validation.Payload;
_Actual change_

2025-02-12 12:42 UTC, alexbishop1 commented on model-dropwizard-4/src/main/java/uk/gov/service/payments/commons/api/validation/AllowedStringsValidator.java
> +import jakarta.validation.ConstraintValidatorContext;
_Actual change_

2025-02-12 12:42 UTC, alexbishop1 commented on model-dropwizard-4/src/main/java/uk/gov/service/payments/commons/api/validation/MapKeyInsensitiveUnique.java
> +import jakarta.validation.Payload;
_Actual change_

2025-02-12 12:42 UTC, alexbishop1 commented on model-dropwizard-4/src/main/java/uk/gov/service/payments/commons/api/validation/MapKeyInsensitiveUniqueValidator.java
> +import jakarta.validation.ConstraintValidatorContext;
_Actual change_

2025-02-12 12:42 UTC, alexbishop1 commented on model-dropwizard-4/src/main/java/uk/gov/service/payments/commons/api/validation/MapKeyLength.java
> +import jakarta.validation.Payload;
_Actual change_

2025-02-12 12:42 UTC, alexbishop1 commented on model-dropwizard-4/src/main/java/uk/gov/service/payments/commons/model/SupportedLanguageJpaConverter.java
> +import jakarta.persistence.Converter;
_Actual change_

2025-02-12 12:42 UTC, alexbishop1 commented on model-dropwizard-4/src/test/java/uk/gov/service/payments/commons/model/charge/ExternalMetadataTest.java
> +import jakarta.validation.Validator;
_Actual change_

2025-02-12 12:42 UTC, alexbishop1 commented on queue-dropwizard-4/pom.xml
> +    </dependencyManagement>
_Actual change_

2025-02-12 12:42 UTC, alexbishop1 commented on testing-dropwizard-4/pom.xml
> +            </dependency>
_Actual change_

2025-02-12 12:42 UTC, alexbishop1 commented on testing-dropwizard-4/pom.xml
> +        <dependency>
_Actual change_: removal of `javax.json:javax.json-api` and `org.glassfish:javax.json` dependencies

2025-02-12 12:42 UTC, alexbishop1 commented on testing-dropwizard-4/pom.xml
> +            <version>3.10.0</version>
This should probably be 3.11.0 to match what’s in the Dropwizard 3 version.

2025-02-12 12:42 UTC, alexbishop1 commented on testing-dropwizard-4/pom.xml
> +            <version>3.26.3</version>
This should probably be 3.27.3 to match what’s in the Dropwizard 3 version.

2025-02-12 12:42 UTC, alexbishop1 commented on utils-dropwizard-4/pom.xml
> +    </dependencyManagement>
_Actual change_

2025-02-12 12:42 UTC, alexbishop1 commented on utils-dropwizard-4/pom.xml
> +            <version>4.2.29</version>
This should probably be 4.2.30 to match what’s in the Dropwizard 3 version.

2025-02-12 12:42 UTC, alexbishop1 commented on validation-dropwizard-4/pom.xml
> +    </dependencyManagement>
_Actual change_

2025-02-12 12:42 UTC, alexbishop1 commented on validation-dropwizard-4/pom.xml
> +        </dependency>
This has lost its version number. Is that intentional?

2025-02-12 12:42 UTC, alexbishop1 commented on validation-dropwizard-4/src/main/java/uk/gov/service/payments/commons/validation/DateValidator.java
> +import jakarta.validation.ConstraintValidatorContext;
_Actual change_

2025-02-12 12:42 UTC, alexbishop1 commented on validation-dropwizard-4/src/main/java/uk/gov/service/payments/commons/validation/ValidDate.java
> +import jakarta.validation.Payload;
_Actual change_

2025-02-12 12:42 UTC, alexbishop1 commented on validation-dropwizard-4/src/main/java/uk/gov/service/payments/commons/validation/ValidDate.java
> +public @interface ValidDate {
This interface is how you validate you have a valid date! 🤣

2025-02-12 13:25 UTC, SandorArpa commented on model-dropwizard-4/pom.xml
> +        </dependency>
It's in DW 3 and dependency is 7.0.5, which is EoL. Hence the upgrade to 8.0.0. However, it seems that it's not needed at all for either modeules.

2025-02-12 14:12 UTC, SandorArpa commented on logging-dropwizard-4/src/main/java/uk/gov/service/payments/logging/SentryAppenderFactory.java
> +public class SentryAppenderFactory extends AbstractAppenderFactory<ILoggingEvent> {
I don't know. TBH I don't understand enough about the Sentry logging to make a call. Other projects do use this class.

2025-03-31 13:07 UTC, alexbishop1 requested changes
I’ve once again annotated any actual changes (cumulative with the ones in the last review). Just a couple of small things.

2025-03-31 13:07 UTC, alexbishop1 commented on utils/pom.xml
> +            <version>${hamcrest.version}</version>
Not sure about this — we’d be relying on projects that import utils having the variable set for the first time and that’s probably significant enough to not tag along with another big change

2025-03-31 14:59 UTC, alexbishop1 approved these changes

2025-03-31 15:02 UTC, merged